theme: jekyll-theme-minimal
title: cim-compare
description: Command line tool for generating CIM model comparison reports.
logo: /assets/img/logo.png
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
