//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.25 at 10:23:56 AM CDT 
//

package org.cimug.compare.logs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CompareResultsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CompareResultsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CompareItem" type="{}CompareItemType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="hasChanges" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompareResultsType", propOrder = { "compareItem" })
public class CompareResults {

	@XmlElement(name = "CompareItem", required = true)
	protected CompareItem compareItem;
	@XmlAttribute(name = "hasChanges")
	protected boolean hasChanges;

	public CompareResults(CompareItem compareItem, boolean hasChanges) {
		super();
		this.compareItem = compareItem;
		this.hasChanges = hasChanges;
	}

	public CompareResults() {
		super();
	}

	/**
	 * Gets the value of the compareItem property.
	 * 
	 * @return possible object is {@link CompareItem }
	 * 
	 */
	public CompareItem getCompareItem() {
		return compareItem;
	}

	/**
	 * Sets the value of the compareItem property.
	 * 
	 * @param value
	 *            allowed object is {@link CompareItem }
	 * 
	 */
	public void setCompareItem(CompareItem value) {
		this.compareItem = value;
	}

	/**
	 * Gets the value of the hasChanges property.
	 * 
	 * @return possible object is {@link boolean }
	 * 
	 */
	public boolean getHasChanges() {
		return hasChanges;
	}

	/**
	 * Sets the value of the hasChanges property.
	 * 
	 * @param value
	 *            allowed object is {@link boolean }
	 * 
	 */
	public void setHasChanges(boolean value) {
		this.hasChanges = value;
	}

}
