//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.25 at 10:23:56 AM CDT 
//

package org.cimug.compare.logs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ComparePackageType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ComparePackageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CompareResults" type="{}CompareResultsType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="guid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="packageID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="comparedBy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="comparedOn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComparePackageType", propOrder = { "compareResults" })
public class ComparePackage {

	@XmlElement(name = "CompareResults", required = true)
	protected CompareResults compareResults;
	@XmlAttribute(name = "name")
	protected String name;
	@XmlAttribute(name = "guid")
	protected String guid;
	@XmlAttribute(name = "packageID")
	protected String packageID;
	@XmlAttribute(name = "comparedBy")
	protected String comparedBy;
	@XmlAttribute(name = "comparedOn")
	protected String comparedOn;

	public ComparePackage(CompareResults compareResults, String name, String guid, String packageID, String comparedBy,
			String comparedOn) {
		super();
		this.compareResults = compareResults;
		this.name = name;
		this.guid = guid;
		this.packageID = packageID;
		this.comparedBy = comparedBy;
		this.comparedOn = comparedOn;
	}

	public ComparePackage() {
		super();
	}

	/**
	 * Gets the value of the compareResults property.
	 * 
	 * @return possible object is {@link CompareResults }
	 * 
	 */
	public CompareResults getCompareResults() {
		return compareResults;
	}

	/**
	 * Sets the value of the compareResults property.
	 * 
	 * @param value
	 *            allowed object is {@link CompareResults }
	 * 
	 */
	public void setCompareResults(CompareResults value) {
		this.compareResults = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the guid property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * Sets the value of the guid property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGuid(String value) {
		this.guid = value;
	}

	/**
	 * Gets the value of the packageID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPackageID() {
		return packageID;
	}

	/**
	 * Sets the value of the packageID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPackageID(String value) {
		this.packageID = value;
	}

	/**
	 * Gets the value of the comparedBy property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComparedBy() {
		return comparedBy;
	}

	/**
	 * Sets the value of the comparedBy property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComparedBy(String value) {
		this.comparedBy = value;
	}

	/**
	 * Gets the value of the comparedOn property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComparedOn() {
		return comparedOn;
	}

	/**
	 * Sets the value of the comparedOn property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComparedOn(String value) {
		this.comparedOn = value;
	}

}
