//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.25 at 10:23:56 AM CDT 
//


package org.cimug.compare.logs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EA.CompareLogType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EA.CompareLogType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ComparePackage" type="{}ComparePackageType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="EA.CompareLog")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EA.CompareLogType", propOrder = {
    "comparePackage"
})
public class EACompareLog {

	@XmlElement(name = "ComparePackage", required = true)
    protected ComparePackage comparePackage;

    public EACompareLog(ComparePackage comparePackage) {
		super();
		this.comparePackage = comparePackage;
	}

    public EACompareLog() {
		super();
	}

    /**
     * Gets the value of the comparePackage property.
     * 
     * @return
     *     possible object is
     *     {@link ComparePackage }
     *     
     */
    public ComparePackage getComparePackage() {
        return comparePackage;
    }

    /**
     * Sets the value of the comparePackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComparePackage }
     *     
     */
    public void setComparePackage(ComparePackage value) {
        this.comparePackage = value;
    }

}
