//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.25 at 10:23:56 AM CDT 
//

package org.cimug.compare.logs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.cimug.compare.logs package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _EACompareLog_QNAME = new QName("", "EA.CompareLog");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema
	 * derived classes for package: org.cimug.compare.logs
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link EACompareLog }
	 * 
	 */
	public EACompareLog createEACompareLog() {
		return new EACompareLog();
	}

	/**
	 * Create an instance of {@link Property }
	 * 
	 */
	public Property createProperty() {
		return new Property();
	}

	/**
	 * Create an instance of {@link Properties }
	 * 
	 */
	public Properties createProperties() {
		return new Properties();
	}

	/**
	 * Create an instance of {@link CompareItem }
	 * 
	 */
	public CompareItem createCompareItem() {
		return new CompareItem();
	}

	/**
	 * Create an instance of {@link CompareResults }
	 * 
	 */
	public CompareResults createCompareResults() {
		return new CompareResults();
	}

	/**
	 * Create an instance of {@link ComparePackage }
	 * 
	 */
	public ComparePackage createComparePackage() {
		return new ComparePackage();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link EACompareLog
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link EACompareLog
	 *         }{@code >}
	 */
	@XmlElementDecl(namespace = "", name = "EA.CompareLog")
	public JAXBElement<EACompareLog> createEACompareLog(EACompareLog value) {
		return new JAXBElement<EACompareLog>(_EACompareLog_QNAME, EACompareLog.class, null, value);
	}

}
