//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.xmi1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for XMI.documentationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XMI.documentationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="XMI.exporter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="XMI.exporterVersion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMI.documentationType", propOrder = { "xmiExporter", "xmiExporterVersion" })
public class XMIDocumentationType {

	@XmlElement(name = "XMI.exporter", required = true)
	protected String xmiExporter;
	@XmlElement(name = "XMI.exporterVersion", required = true)
	protected String xmiExporterVersion;

	/**
	 * Gets the value of the xmiExporter property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXMIExporter() {
		return xmiExporter;
	}

	/**
	 * Sets the value of the xmiExporter property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXMIExporter(String value) {
		this.xmiExporter = value;
	}

	/**
	 * Gets the value of the xmiExporterVersion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXMIExporterVersion() {
		return xmiExporterVersion;
	}

	/**
	 * Sets the value of the xmiExporterVersion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXMIExporterVersion(String value) {
		this.xmiExporterVersion = value;
	}

}
