//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.xmi1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for XMI.headerType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XMI.headerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="XMI.documentation" type="{}XMI.documentationType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMI.headerType", propOrder = { "xmiDocumentation" })
public class XMIHeaderType {

	@XmlElement(name = "XMI.documentation", required = true)
	protected XMIDocumentationType xmiDocumentation;

	/**
	 * Gets the value of the xmiDocumentation property.
	 * 
	 * @return possible object is {@link XMIDocumentationType }
	 * 
	 */
	public XMIDocumentationType getXMIDocumentation() {
		return xmiDocumentation;
	}

	/**
	 * Sets the value of the xmiDocumentation property.
	 * 
	 * @param value
	 *            allowed object is {@link XMIDocumentationType }
	 * 
	 */
	public void setXMIDocumentation(XMIDocumentationType value) {
		this.xmiDocumentation = value;
	}

}
