//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.uml1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.cimug.compare.uml1_3.ifaces.KeyIdentifier;
import org.cimug.compare.uml1_3.ifaces.ModelElementTaggedValueContainer;
import org.cimug.compare.uml1_3.ifaces.NamedType;

/**
 * <p>
 * Java class for AttributeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Attribute.initialValue" type="{omg.org/UML1.3}Attribute.initialValueType"/&gt;
 *         &lt;element name="StructuralFeature.type" type="{omg.org/UML1.3}StructuralFeature.typeType"/&gt;
 *         &lt;element name="ModelElement.stereotype" type="{omg.org/UML1.3}ModelElement.stereotypeType" minOccurs="0"/&gt;
 *         &lt;element name="ModelElement.taggedValue" type="{omg.org/UML1.3}ModelElement.taggedValueType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="changeable" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="visibility" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ownerScope" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="targetScope" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeType", propOrder = { "attributeInitialValue", "structuralFeatureType",
		"modelElementStereotype", "modelElementTaggedValue" })
public class AttributeType implements ModelElementTaggedValueContainer, NamedType, KeyIdentifier {

	@XmlElement(name = "Attribute.initialValue", required = true)
	protected AttributeInitialValueType attributeInitialValue;
	@XmlElement(name = "StructuralFeature.type", required = true)
	protected StructuralFeatureTypeType structuralFeatureType;
	@XmlElement(name = "ModelElement.stereotype")
	protected ModelElementStereotypeType modelElementStereotype;
	@XmlElement(name = "ModelElement.taggedValue", required = true)
	protected ModelElementTaggedValue modelElementTaggedValue;
	@XmlAttribute(name = "name")
	protected String name;
	@XmlAttribute(name = "changeable")
	protected String changeable;
	@XmlAttribute(name = "visibility")
	protected String visibility;
	@XmlAttribute(name = "ownerScope")
	protected String ownerScope;
	@XmlAttribute(name = "targetScope")
	protected String targetScope;

	public AttributeType(AttributeInitialValueType attributeInitialValue,
			StructuralFeatureTypeType structuralFeatureType, ModelElementStereotypeType modelElementStereotype,
			ModelElementTaggedValue modelElementTaggedValue, String name, String changeable, String visibility,
			String ownerScope, String targetScope) {
		super();
		this.attributeInitialValue = attributeInitialValue;
		this.structuralFeatureType = structuralFeatureType;
		this.modelElementStereotype = modelElementStereotype;
		this.modelElementTaggedValue = modelElementTaggedValue;
		this.name = name;
		this.changeable = changeable;
		this.visibility = visibility;
		this.ownerScope = ownerScope;
		this.targetScope = targetScope;
	}

	public AttributeType() {
		super();
	}

	/**
	 * Gets the value of the attributeInitialValue property.
	 * 
	 * @return possible object is {@link AttributeInitialValueType }
	 * 
	 */
	public AttributeInitialValueType getAttributeInitialValue() {
		return attributeInitialValue;
	}

	/**
	 * Sets the value of the attributeInitialValue property.
	 * 
	 * @param value
	 *            allowed object is {@link AttributeInitialValueType }
	 * 
	 */
	public void setAttributeInitialValue(AttributeInitialValueType value) {
		this.attributeInitialValue = value;
	}

	/**
	 * Gets the value of the structuralFeatureType property.
	 * 
	 * @return possible object is {@link StructuralFeatureTypeType }
	 * 
	 */
	public StructuralFeatureTypeType getStructuralFeatureType() {
		return structuralFeatureType;
	}

	/**
	 * Sets the value of the structuralFeatureType property.
	 * 
	 * @param value
	 *            allowed object is {@link StructuralFeatureTypeType }
	 * 
	 */
	public void setStructuralFeatureType(StructuralFeatureTypeType value) {
		this.structuralFeatureType = value;
	}

	/**
	 * Gets the value of the modelElementStereotype property.
	 * 
	 * @return possible object is {@link ModelElementStereotypeType }
	 * 
	 */
	public ModelElementStereotypeType getModelElementStereotype() {
		return modelElementStereotype;
	}

	/**
	 * Sets the value of the modelElementStereotype property.
	 * 
	 * @param value
	 *            allowed object is {@link ModelElementStereotypeType }
	 * 
	 */
	public void setModelElementStereotype(ModelElementStereotypeType value) {
		this.modelElementStereotype = value;
	}

	/**
	 * Gets the value of the modelElementTaggedValue property.
	 * 
	 * @return possible object is {@link ModelElementTaggedValue }
	 * 
	 */
	public ModelElementTaggedValue getModelElementTaggedValue() {
		return modelElementTaggedValue;
	}

	/**
	 * Sets the value of the modelElementTaggedValue property.
	 * 
	 * @param value
	 *            allowed object is {@link ModelElementTaggedValue }
	 * 
	 */
	public void setModelElementTaggedValue(ModelElementTaggedValue value) {
		this.modelElementTaggedValue = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the changeable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChangeable() {
		return changeable;
	}

	/**
	 * Sets the value of the changeable property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChangeable(String value) {
		this.changeable = value;
	}

	/**
	 * Gets the value of the visibility property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVisibility() {
		return visibility;
	}

	/**
	 * Sets the value of the visibility property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVisibility(String value) {
		this.visibility = value;
	}

	/**
	 * Gets the value of the ownerScope property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOwnerScope() {
		return ownerScope;
	}

	/**
	 * Sets the value of the ownerScope property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOwnerScope(String value) {
		this.ownerScope = value;
	}

	/**
	 * Gets the value of the targetScope property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTargetScope() {
		return targetScope;
	}

	/**
	 * Sets the value of the targetScope property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTargetScope(String value) {
		this.targetScope = value;
	}

	@Override
	public String getKey() {
		return getTheValue("ea_guid");
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AttributeType other = (AttributeType) obj;
		if (getKey() == null) {
			if (other.getKey() != null)
				return false;
		} else if (!getKey().equals(other.getKey()))
			return false;
		return true;
	}
	
	

}
