//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.uml1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Collaboration.interactionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Collaboration.interactionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Interaction" type="{omg.org/UML1.3}InteractionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Collaboration.interactionType", propOrder = { "interaction" })
public class CollaborationInteractionType {

	@XmlElement(name = "Interaction")
	protected InteractionType interaction;

	/**
	 * Gets the value of the interaction property.
	 * 
	 * @return possible object is {@link InteractionType }
	 * 
	 */
	public InteractionType getInteraction() {
		return interaction;
	}

	/**
	 * Sets the value of the interaction property.
	 * 
	 * @param value
	 *            allowed object is {@link InteractionType }
	 * 
	 */
	public void setInteraction(InteractionType value) {
		this.interaction = value;
	}

}
