//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.uml1_3;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;

import org.cimug.compare.uml1_3.ifaces.NamedType;

/**
 * <p>
 * Java class for DependencyType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DependencyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ModelElement.stereotype" type="{omg.org/UML1.3}ModelElement.stereotypeType" minOccurs="0"/&gt;
 *         &lt;element name="ModelElement.taggedValue" type="{omg.org/UML1.3}ModelElement.taggedValueType" minOccurs="0"/&gt;
 *         &lt;element name="Classifier.feature" type="{omg.org/UML1.3}Classifier.featureType" minOccurs="0"/&gt;
 *         &lt;element name="Association.connection" type="{omg.org/UML1.3}Association.connectionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="client" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="supplier" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="xmi.id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="visibility" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="namespace" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isRoot" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isLeaf" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isAbstract" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isActive" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="subtype" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="supertype" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DependencyType", propOrder = { "content" })
public class DependencyType implements NamedType {

	@XmlElementRefs({
			@XmlElementRef(name = "ModelElement.stereotype", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "ModelElement.taggedValue", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "Classifier.feature", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "Association.connection", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false) })
	@XmlMixed
	protected List<Serializable> content;
	@XmlAttribute(name = "client")
	protected String client;
	@XmlAttribute(name = "supplier")
	protected String supplier;
	@XmlAttribute(name = "xmi.id")
	protected String xmiId;
	@XmlAttribute(name = "visibility")
	protected String visibility;
	@XmlAttribute(name = "namespace")
	protected String namespace;
	@XmlAttribute(name = "name")
	protected String name;
	@XmlAttribute(name = "isRoot")
	protected String isRoot;
	@XmlAttribute(name = "isLeaf")
	protected String isLeaf;
	@XmlAttribute(name = "isAbstract")
	protected String isAbstract;
	@XmlAttribute(name = "isActive")
	protected String isActive;
	@XmlAttribute(name = "subtype")
	protected String subtype;
	@XmlAttribute(name = "supertype")
	protected String supertype;

	public DependencyType(List<Serializable> content, String client, String supplier, String xmiId, String visibility,
			String namespace, String name, String isRoot, String isLeaf, String isAbstract, String isActive,
			String subtype, String supertype) {
		super();
		this.content = content;
		this.client = client;
		this.supplier = supplier;
		this.xmiId = xmiId;
		this.visibility = visibility;
		this.namespace = namespace;
		this.name = name;
		this.isRoot = isRoot;
		this.isLeaf = isLeaf;
		this.isAbstract = isAbstract;
		this.isActive = isActive;
		this.subtype = subtype;
		this.supertype = supertype;
	}

	public DependencyType() {
		super();
	}

	/**
	 * Gets the value of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link JAXBElement
	 * }{@code <}{@link ModelElementStereotypeType }{@code >} {@link JAXBElement
	 * }{@code <}{@link ModelElementTaggedValue }{@code >} {@link JAXBElement
	 * }{@code <}{@link ClassifierFeatureType }{@code >} {@link JAXBElement
	 * }{@code <}{@link AssociationConnectionType }{@code >} {@link String }
	 * 
	 * 
	 */
	public List<Serializable> getContent() {
		if (content == null) {
			content = new ArrayList<Serializable>();
		}
		return this.content;
	}

	/**
	 * Gets the value of the client property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClient() {
		return client;
	}

	/**
	 * Sets the value of the client property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClient(String value) {
		this.client = value;
	}

	/**
	 * Gets the value of the supplier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * Sets the value of the supplier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSupplier(String value) {
		this.supplier = value;
	}

	/**
	 * Gets the value of the xmiId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXmiId() {
		return xmiId;
	}

	/**
	 * Sets the value of the xmiId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXmiId(String value) {
		this.xmiId = value;
	}

	/**
	 * Gets the value of the visibility property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVisibility() {
		return visibility;
	}

	/**
	 * Sets the value of the visibility property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVisibility(String value) {
		this.visibility = value;
	}

	/**
	 * Gets the value of the namespace property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNamespace() {
		return namespace;
	}

	/**
	 * Sets the value of the namespace property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNamespace(String value) {
		this.namespace = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the isRoot property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIsRoot() {
		return isRoot;
	}

	/**
	 * Sets the value of the isRoot property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIsRoot(String value) {
		this.isRoot = value;
	}

	/**
	 * Gets the value of the isLeaf property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIsLeaf() {
		return isLeaf;
	}

	/**
	 * Sets the value of the isLeaf property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIsLeaf(String value) {
		this.isLeaf = value;
	}

	/**
	 * Gets the value of the isAbstract property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIsAbstract() {
		return isAbstract;
	}

	/**
	 * Sets the value of the isAbstract property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIsAbstract(String value) {
		this.isAbstract = value;
	}

	/**
	 * Gets the value of the isActive property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIsActive() {
		return isActive;
	}

	/**
	 * Sets the value of the isActive property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIsActive(String value) {
		this.isActive = value;
	}

	/**
	 * Gets the value of the subtype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubtype() {
		return subtype;
	}

	/**
	 * Sets the value of the subtype property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubtype(String value) {
		this.subtype = value;
	}

	/**
	 * Gets the value of the supertype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSupertype() {
		return supertype;
	}

	/**
	 * Sets the value of the supertype property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSupertype(String value) {
		this.supertype = value;
	}

}
