//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.uml1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.cimug.compare.uml1_3.ifaces.NamedType;

/**
 * <p>
 * Java class for DiagramType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DiagramType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ModelElement.taggedValue" type="{omg.org/UML1.3}ModelElement.taggedValueType"/&gt;
 *         &lt;element name="Diagram.element" type="{omg.org/UML1.3}Diagram.elementType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="xmi.id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="diagramType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="owner" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="toolName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiagramType", propOrder = { "modelElementTaggedValue", "diagramElement" })
@XmlRootElement(name = "Diagram")
public class Diagram implements NamedType {

	@XmlElement(name = "ModelElement.taggedValue", required = true)
	protected ModelElementTaggedValue modelElementTaggedValue;
	@XmlElement(name = "Diagram.element")
	protected DiagramElementType diagramElement;
	@XmlAttribute(name = "name")
	protected String name;
	@XmlAttribute(name = "xmi.id")
	protected String xmiId;
	@XmlAttribute(name = "diagramType")
	protected String diagramType;
	@XmlAttribute(name = "owner")
	protected String owner;
	@XmlAttribute(name = "toolName")
	protected String toolName;

	public Diagram(ModelElementTaggedValue modelElementTaggedValue, DiagramElementType diagramElement, String name,
			String xmiId, String diagramType, String owner, String toolName) {
		super();
		this.modelElementTaggedValue = modelElementTaggedValue;
		this.diagramElement = diagramElement;
		this.name = name;
		this.xmiId = xmiId;
		this.diagramType = diagramType;
		this.owner = owner;
		this.toolName = toolName;
	}

	public Diagram() {
		super();

	}

	/**
	 * Gets the value of the modelElementTaggedValue property.
	 * 
	 * @return possible object is {@link ModelElementTaggedValue }
	 * 
	 */
	public ModelElementTaggedValue getModelElementTaggedValue() {
		return modelElementTaggedValue;
	}

	/**
	 * Sets the value of the modelElementTaggedValue property.
	 * 
	 * @param value
	 *            allowed object is {@link ModelElementTaggedValue }
	 * 
	 */
	public void setModelElementTaggedValue(ModelElementTaggedValue value) {
		this.modelElementTaggedValue = value;
	}

	/**
	 * Gets the value of the diagramElement property.
	 * 
	 * @return possible object is {@link DiagramElementType }
	 * 
	 */
	public DiagramElementType getDiagramElement() {
		return diagramElement;
	}

	/**
	 * Sets the value of the diagramElement property.
	 * 
	 * @param value
	 *            allowed object is {@link DiagramElementType }
	 * 
	 */
	public void setDiagramElement(DiagramElementType value) {
		this.diagramElement = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the xmiId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXmiId() {
		return xmiId;
	}

	/**
	 * Sets the value of the xmiId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXmiId(String value) {
		this.xmiId = value;
	}

	/**
	 * Gets the value of the diagramType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDiagramType() {
		return diagramType;
	}

	/**
	 * Sets the value of the diagramType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDiagramType(String value) {
		this.diagramType = value;
	}

	/**
	 * Gets the value of the owner property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * Sets the value of the owner property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOwner(String value) {
		this.owner = value;
	}

	/**
	 * Gets the value of the toolName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getToolName() {
		return toolName;
	}

	/**
	 * Sets the value of the toolName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setToolName(String value) {
		this.toolName = value;
	}

}
