//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.uml1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ModelElement.stereotypeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ModelElement.stereotypeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Stereotype" type="{omg.org/UML1.3}StereotypeType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelElement.stereotypeType", propOrder = { "stereotype" })
public class ModelElementStereotypeType {

	@XmlElement(name = "Stereotype", required = true)
	protected StereotypeType stereotype;

    public ModelElementStereotypeType(StereotypeType stereotype) {
		super();
		this.stereotype = stereotype;
	}

    public ModelElementStereotypeType() {
		super();
	}
	/**
	 * Gets the value of the stereotype property.
	 * 
	 * @return possible object is {@link StereotypeType }
	 * 
	 */
	public StereotypeType getStereotype() {
		return stereotype;
	}

	/**
	 * Sets the value of the stereotype property.
	 * 
	 * @param value
	 *            allowed object is {@link StereotypeType }
	 * 
	 */
	public void setStereotype(StereotypeType value) {
		this.stereotype = value;
	}

}
