//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.uml1_3;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ModelElement.taggedValueType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ModelElement.taggedValueType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TaggedValue" type="{omg.org/UML1.3}TaggedValueType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelElement.taggedValueType", propOrder = { "taggedValues" })
@XmlRootElement(name = "ModelElement.taggedValue")
public class ModelElementTaggedValue {

	@XmlElement(name = "TaggedValue")
	protected List<TaggedValueType> taggedValues;

	public ModelElementTaggedValue(List<TaggedValueType> taggedValues) {
		super();
		this.taggedValues = taggedValues;
	}

	public ModelElementTaggedValue() {
		super();
	}

	/**
	 * Gets the value of the taggedValues property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the taggedValues property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTaggedValues().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link TaggedValueType }
	 * 
	 * 
	 */
	public List<TaggedValueType> getTaggedValues() {
		if (taggedValues == null) {
			taggedValues = new ArrayList<TaggedValueType>();
		}
		return this.taggedValues;
	}

	/**
	 * A non-generated convenience method.
	 * 
	 * @param tagName
	 * @return TaggedValueType
	 */
	public TaggedValueType getTaggedValue(String tagName) {
		for (TaggedValueType tv : getTaggedValues()) {
			if (tv.getTag().equals(tagName)) {
				return tv;
			}
		}
		return null;
	}

	@Override
	public String toString() {
		return "ModelElementTaggedValue [taggedValues = " + taggedValues + "]";
	}

}
