//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.uml1_3;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;

import org.cimug.compare.uml1_3.ifaces.OwnedElementsContainer;

/**
 * <p>
 * Java class for Namespace.ownedElementType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Namespace.ownedElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="ClassifierRole" type="{omg.org/UML1.3}ClassifierRoleType"/&gt;
 *         &lt;element name="Class" type="{omg.org/UML1.3}ClassType"/&gt;
 *         &lt;element name="Association" type="{omg.org/UML1.3}AssociationType"/&gt;
 *         &lt;element name="Generalization" type="{omg.org/UML1.3}GeneralizationType"/&gt;
 *         &lt;element name="Comment" type="{omg.org/UML1.3}CommentType"/&gt;
 *         &lt;element name="Collaboration" type="{omg.org/UML1.3}CollaborationType"/&gt;
 *         &lt;element name="Package" type="{omg.org/UML1.3}PackageType"/&gt;
 *         &lt;element name="AssociationRole" type="{omg.org/UML1.3}AssociationRoleType"/&gt;
 *         &lt;element name="Dependency" type="{omg.org/UML1.3}DependencyType"/&gt;
 *         &lt;element name="DataType" type="{omg.org/UML1.3}DataTypeType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Namespace.ownedElementType", propOrder = { "content" })
public class NamespaceOwnedElementType implements OwnedElementsContainer {

	@XmlElementRefs({
			@XmlElementRef(name = "ClassifierRole", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "Class", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "Association", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "Generalization", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "Comment", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "Collaboration", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "Package", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "AssociationRole", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "Dependency", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "DataType", namespace = "omg.org/UML1.3", type = JAXBElement.class, required = false) })
	@XmlMixed
	protected List<Serializable> content;

	public NamespaceOwnedElementType(List<Serializable> content) {
		super();
		this.content = content;
	}

	public NamespaceOwnedElementType() {
		super();
	}

	/**
	 * Gets the value of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link JAXBElement
	 * }{@code <}{@link ClassifierRoleType }{@code >} {@link JAXBElement
	 * }{@code <}{@link ClassType }{@code >} {@link JAXBElement
	 * }{@code <}{@link AssociationType }{@code >} {@link JAXBElement
	 * }{@code <}{@link GeneralizationType }{@code >} {@link JAXBElement
	 * }{@code <}{@link CommentType }{@code >} {@link JAXBElement
	 * }{@code <}{@link CollaborationType }{@code >} {@link JAXBElement
	 * }{@code <}{@link PackageType }{@code >} {@link JAXBElement
	 * }{@code <}{@link AssociationRoleType }{@code >} {@link JAXBElement
	 * }{@code <}{@link DependencyType }{@code >} {@link JAXBElement
	 * }{@code <}{@link DataTypeType }{@code >} {@link String }
	 * 
	 * 
	 */
	public List<Serializable> getContent() {
		if (content == null) {
			content = new ArrayList<Serializable>();
		}
		return this.content;
	}

	@Override
	public String toString() {
		return "NamespaceOwnedElementType [content = " + this.content + "]";
	}

}
