//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

package org.cimug.compare.uml1_3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.osii.cim.uml1_3 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _GeneralizationTypeModelElementStereotype_QNAME = new QName("omg.org/UML1.3",
			"ModelElement.stereotype");
	private final static QName _GeneralizationTypeModelElementTaggedValue_QNAME = new QName("omg.org/UML1.3",
			"ModelElement.taggedValue");
	private final static QName _GeneralizationTypeClassifierFeature_QNAME = new QName("omg.org/UML1.3",
			"Classifier.feature");
	private final static QName _GeneralizationTypeAssociationConnection_QNAME = new QName("omg.org/UML1.3",
			"Association.connection");
	private final static QName _CollaborationTypeNamespaceOwnedElement_QNAME = new QName("omg.org/UML1.3",
			"Namespace.ownedElement");
	private final static QName _CollaborationTypeCollaborationInteraction_QNAME = new QName("omg.org/UML1.3",
			"Collaboration.interaction");
	private final static QName _CollaborationTypeCollaborationInteractionInteraction_QNAME = new QName("omg.org/UML1.3",
			"Interaction");
	private final static QName _NamespaceOwnedElementTypeClassifierRole_QNAME = new QName("omg.org/UML1.3",
			"ClassifierRole");
	private final static QName _NamespaceOwnedElementTypeClass_QNAME = new QName("omg.org/UML1.3", "Class");
	private final static QName _NamespaceOwnedElementTypeAssociation_QNAME = new QName("omg.org/UML1.3", "Association");
	private final static QName _NamespaceOwnedElementTypeGeneralization_QNAME = new QName("omg.org/UML1.3",
			"Generalization");
	private final static QName _NamespaceOwnedElementTypeComment_QNAME = new QName("omg.org/UML1.3", "Comment");
	private final static QName _NamespaceOwnedElementTypeCollaboration_QNAME = new QName("omg.org/UML1.3",
			"Collaboration");
	private final static QName _NamespaceOwnedElementTypePackage_QNAME = new QName("omg.org/UML1.3", "Package");
	private final static QName _NamespaceOwnedElementTypeAssociationRole_QNAME = new QName("omg.org/UML1.3",
			"AssociationRole");
	private final static QName _NamespaceOwnedElementTypeDependency_QNAME = new QName("omg.org/UML1.3", "Dependency");
	private final static QName _NamespaceOwnedElementTypeDataType_QNAME = new QName("omg.org/UML1.3", "DataType");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema
	 * derived classes for package: com.osii.cim.uml1_3
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link CollaborationType }
	 * 
	 */
	public CollaborationType createCollaborationType() {
		return new CollaborationType();
	}

	/**
	 * Create an instance of {@link Model }
	 * 
	 */
	public Model createModel() {
		return new Model();
	}

	/**
	 * Create an instance of {@link NamespaceOwnedElementType }
	 * 
	 */
	public NamespaceOwnedElementType createNamespaceOwnedElementType() {
		return new NamespaceOwnedElementType();
	}

	/**
	 * Create an instance of {@link Diagram }
	 * 
	 */
	public Diagram createDiagram() {
		return new Diagram();
	}

	/**
	 * Create an instance of {@link ModelElementTaggedValue }
	 * 
	 */
	public ModelElementTaggedValue createModelElementTaggedValue() {
		return new ModelElementTaggedValue();
	}

	/**
	 * Create an instance of {@link DiagramElementType }
	 * 
	 */
	public DiagramElementType createDiagramElementType() {
		return new DiagramElementType();
	}

	/**
	 * Create an instance of {@link TaggedValueType }
	 * 
	 */
	public TaggedValueType createTaggedValueType() {
		return new TaggedValueType();
	}

	/**
	 * Create an instance of {@link ClassType }
	 * 
	 */
	public ClassType createClassType() {
		return new ClassType();
	}

	/**
	 * Create an instance of {@link ClassifierRoleType }
	 * 
	 */
	public ClassifierRoleType createClassifierRoleType() {
		return new ClassifierRoleType();
	}

	/**
	 * Create an instance of {@link DependencyType }
	 * 
	 */
	public DependencyType createDependencyType() {
		return new DependencyType();
	}

	/**
	 * Create an instance of {@link CommentType }
	 * 
	 */
	public CommentType createCommentType() {
		return new CommentType();
	}

	/**
	 * Create an instance of {@link ExpressionType }
	 * 
	 */
	public ExpressionType createExpressionType() {
		return new ExpressionType();
	}

	/**
	 * Create an instance of {@link AttributeInitialValueType }
	 * 
	 */
	public AttributeInitialValueType createAttributeInitialValueType() {
		return new AttributeInitialValueType();
	}

	/**
	 * Create an instance of {@link ClassifierType }
	 * 
	 */
	public ClassifierType createClassifierType() {
		return new ClassifierType();
	}

	/**
	 * Create an instance of {@link StructuralFeatureTypeType }
	 * 
	 */
	public StructuralFeatureTypeType createStructuralFeatureTypeType() {
		return new StructuralFeatureTypeType();
	}

	/**
	 * Create an instance of {@link AttributeType }
	 * 
	 */
	public AttributeType createAttributeType() {
		return new AttributeType();
	}

	/**
	 * Create an instance of {@link ClassifierFeatureType }
	 * 
	 */
	public ClassifierFeatureType createClassifierFeatureType() {
		return new ClassifierFeatureType();
	}

	/**
	 * Create an instance of {@link StereotypeType }
	 * 
	 */
	public StereotypeType createStereotypeType() {
		return new StereotypeType();
	}

	/**
	 * Create an instance of {@link ModelElementStereotypeType }
	 * 
	 */
	public ModelElementStereotypeType createModelElementStereotypeType() {
		return new ModelElementStereotypeType();
	}

	/**
	 * Create an instance of {@link AssociationEndType }
	 * 
	 */
	public AssociationEndType createAssociationEndType() {
		return new AssociationEndType();
	}

	/**
	 * Create an instance of {@link AssociationConnectionType }
	 * 
	 */
	public AssociationConnectionType createAssociationConnectionType() {
		return new AssociationConnectionType();
	}

	/**
	 * Create an instance of {@link AssociationType }
	 * 
	 */
	public AssociationType createAssociationType() {
		return new AssociationType();
	}

	/**
	 * Create an instance of {@link GeneralizationType }
	 * 
	 */
	public GeneralizationType createGeneralizationType() {
		return new GeneralizationType();
	}

	/**
	 * Create an instance of {@link PackageType }
	 * 
	 */
	public PackageType createPackageType() {
		return new PackageType();
	}

	/**
	 * Create an instance of {@link AssociationEndRoleType }
	 * 
	 */
	public AssociationEndRoleType createAssociationEndRoleType() {
		return new AssociationEndRoleType();
	}

	/**
	 * Create an instance of {@link AssociationRoleType }
	 * 
	 */
	public AssociationRoleType createAssociationRoleType() {
		return new AssociationRoleType();
	}

	/**
	 * Create an instance of {@link ConstraintType }
	 * 
	 */
	public ConstraintType createConstraintType() {
		return new ConstraintType();
	}

	/**
	 * Create an instance of {@link ModelElementConstraintType }
	 * 
	 */
	public ModelElementConstraintType createModelElementConstraintType() {
		return new ModelElementConstraintType();
	}

	/**
	 * Create an instance of {@link DataTypeType }
	 * 
	 */
	public DataTypeType createDataTypeType() {
		return new DataTypeType();
	}

	/**
	 * Create an instance of {@link DiagramElement }
	 * 
	 */
	public DiagramElement createDiagramElement() {
		return new DiagramElement();
	}

	/**
	 * Create an instance of {@link MessageType }
	 * 
	 */
	public MessageType createMessageType() {
		return new MessageType();
	}

	/**
	 * Create an instance of {@link InteractionMessageType }
	 * 
	 */
	public InteractionMessageType createInteractionMessageType() {
		return new InteractionMessageType();
	}

	/**
	 * Create an instance of {@link InteractionType }
	 * 
	 */
	public InteractionType createInteractionType() {
		return new InteractionType();
	}

	/**
	 * Create an instance of {@link CollaborationInteractionType }
	 * 
	 */
	public CollaborationInteractionType createCollaborationInteractionType() {
		return new CollaborationInteractionType();
	}

	/**
	 * Create an instance of {@link CollaborationType.CollaborationInteraction }
	 * 
	 */
	public CollaborationType.CollaborationInteraction createCollaborationTypeCollaborationInteraction() {
		return new CollaborationType.CollaborationInteraction();
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementStereotypeType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementStereotypeType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.stereotype", scope = GeneralizationType.class)
	public JAXBElement<ModelElementStereotypeType> createGeneralizationTypeModelElementStereotype(
			ModelElementStereotypeType value) {
		return new JAXBElement<ModelElementStereotypeType>(_GeneralizationTypeModelElementStereotype_QNAME,
				ModelElementStereotypeType.class, GeneralizationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementTaggedValue }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementTaggedValue }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.taggedValue", scope = GeneralizationType.class)
	public JAXBElement<ModelElementTaggedValue> createGeneralizationTypeModelElementTaggedValue(
			ModelElementTaggedValue value) {
		return new JAXBElement<ModelElementTaggedValue>(_GeneralizationTypeModelElementTaggedValue_QNAME,
				ModelElementTaggedValue.class, GeneralizationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ClassifierFeatureType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ClassifierFeatureType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Classifier.feature", scope = GeneralizationType.class)
	public JAXBElement<ClassifierFeatureType> createGeneralizationTypeClassifierFeature(ClassifierFeatureType value) {
		return new JAXBElement<ClassifierFeatureType>(_GeneralizationTypeClassifierFeature_QNAME,
				ClassifierFeatureType.class, GeneralizationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link AssociationConnectionType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link AssociationConnectionType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Association.connection", scope = GeneralizationType.class)
	public JAXBElement<AssociationConnectionType> createGeneralizationTypeAssociationConnection(
			AssociationConnectionType value) {
		return new JAXBElement<AssociationConnectionType>(_GeneralizationTypeAssociationConnection_QNAME,
				AssociationConnectionType.class, GeneralizationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementStereotypeType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementStereotypeType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.stereotype", scope = AssociationType.class)
	public JAXBElement<ModelElementStereotypeType> createAssociationTypeModelElementStereotype(
			ModelElementStereotypeType value) {
		return new JAXBElement<ModelElementStereotypeType>(_GeneralizationTypeModelElementStereotype_QNAME,
				ModelElementStereotypeType.class, AssociationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementTaggedValue }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementTaggedValue }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.taggedValue", scope = AssociationType.class)
	public JAXBElement<ModelElementTaggedValue> createAssociationTypeModelElementTaggedValue(
			ModelElementTaggedValue value) {
		return new JAXBElement<ModelElementTaggedValue>(_GeneralizationTypeModelElementTaggedValue_QNAME,
				ModelElementTaggedValue.class, AssociationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ClassifierFeatureType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ClassifierFeatureType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Classifier.feature", scope = AssociationType.class)
	public JAXBElement<ClassifierFeatureType> createAssociationTypeClassifierFeature(ClassifierFeatureType value) {
		return new JAXBElement<ClassifierFeatureType>(_GeneralizationTypeClassifierFeature_QNAME,
				ClassifierFeatureType.class, AssociationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link AssociationConnectionType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link AssociationConnectionType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Association.connection", scope = AssociationType.class)
	public JAXBElement<AssociationConnectionType> createAssociationTypeAssociationConnection(
			AssociationConnectionType value) {
		return new JAXBElement<AssociationConnectionType>(_GeneralizationTypeAssociationConnection_QNAME,
				AssociationConnectionType.class, AssociationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementStereotypeType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementStereotypeType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.stereotype", scope = CommentType.class)
	public JAXBElement<ModelElementStereotypeType> createCommentTypeModelElementStereotype(
			ModelElementStereotypeType value) {
		return new JAXBElement<ModelElementStereotypeType>(_GeneralizationTypeModelElementStereotype_QNAME,
				ModelElementStereotypeType.class, CommentType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementTaggedValue }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementTaggedValue }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.taggedValue", scope = CommentType.class)
	public JAXBElement<ModelElementTaggedValue> createCommentTypeModelElementTaggedValue(
			ModelElementTaggedValue value) {
		return new JAXBElement<ModelElementTaggedValue>(_GeneralizationTypeModelElementTaggedValue_QNAME,
				ModelElementTaggedValue.class, CommentType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ClassifierFeatureType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ClassifierFeatureType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Classifier.feature", scope = CommentType.class)
	public JAXBElement<ClassifierFeatureType> createCommentTypeClassifierFeature(ClassifierFeatureType value) {
		return new JAXBElement<ClassifierFeatureType>(_GeneralizationTypeClassifierFeature_QNAME,
				ClassifierFeatureType.class, CommentType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link AssociationConnectionType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link AssociationConnectionType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Association.connection", scope = CommentType.class)
	public JAXBElement<AssociationConnectionType> createCommentTypeAssociationConnection(
			AssociationConnectionType value) {
		return new JAXBElement<AssociationConnectionType>(_GeneralizationTypeAssociationConnection_QNAME,
				AssociationConnectionType.class, CommentType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementStereotypeType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementStereotypeType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.stereotype", scope = DependencyType.class)
	public JAXBElement<ModelElementStereotypeType> createDependencyTypeModelElementStereotype(
			ModelElementStereotypeType value) {
		return new JAXBElement<ModelElementStereotypeType>(_GeneralizationTypeModelElementStereotype_QNAME,
				ModelElementStereotypeType.class, DependencyType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementTaggedValue }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementTaggedValue }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.taggedValue", scope = DependencyType.class)
	public JAXBElement<ModelElementTaggedValue> createDependencyTypeModelElementTaggedValue(
			ModelElementTaggedValue value) {
		return new JAXBElement<ModelElementTaggedValue>(_GeneralizationTypeModelElementTaggedValue_QNAME,
				ModelElementTaggedValue.class, DependencyType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ClassifierFeatureType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ClassifierFeatureType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Classifier.feature", scope = DependencyType.class)
	public JAXBElement<ClassifierFeatureType> createDependencyTypeClassifierFeature(ClassifierFeatureType value) {
		return new JAXBElement<ClassifierFeatureType>(_GeneralizationTypeClassifierFeature_QNAME,
				ClassifierFeatureType.class, DependencyType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link AssociationConnectionType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link AssociationConnectionType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Association.connection", scope = DependencyType.class)
	public JAXBElement<AssociationConnectionType> createDependencyTypeAssociationConnection(
			AssociationConnectionType value) {
		return new JAXBElement<AssociationConnectionType>(_GeneralizationTypeAssociationConnection_QNAME,
				AssociationConnectionType.class, DependencyType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link NamespaceOwnedElementType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link NamespaceOwnedElementType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Namespace.ownedElement", scope = CollaborationType.class)
	public JAXBElement<NamespaceOwnedElementType> createCollaborationTypeNamespaceOwnedElement(
			NamespaceOwnedElementType value) {
		return new JAXBElement<NamespaceOwnedElementType>(_CollaborationTypeNamespaceOwnedElement_QNAME,
				NamespaceOwnedElementType.class, CollaborationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link CollaborationType.CollaborationInteraction }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link CollaborationType.CollaborationInteraction }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Collaboration.interaction", scope = CollaborationType.class)
	public JAXBElement<CollaborationType.CollaborationInteraction> createCollaborationTypeCollaborationInteraction(
			CollaborationType.CollaborationInteraction value) {
		return new JAXBElement<CollaborationType.CollaborationInteraction>(
				_CollaborationTypeCollaborationInteraction_QNAME, CollaborationType.CollaborationInteraction.class,
				CollaborationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementStereotypeType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementStereotypeType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.stereotype", scope = CollaborationType.class)
	public JAXBElement<ModelElementStereotypeType> createCollaborationTypeModelElementStereotype(
			ModelElementStereotypeType value) {
		return new JAXBElement<ModelElementStereotypeType>(_GeneralizationTypeModelElementStereotype_QNAME,
				ModelElementStereotypeType.class, CollaborationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementTaggedValue }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementTaggedValue }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.taggedValue", scope = CollaborationType.class)
	public JAXBElement<ModelElementTaggedValue> createCollaborationTypeModelElementTaggedValue(
			ModelElementTaggedValue value) {
		return new JAXBElement<ModelElementTaggedValue>(_GeneralizationTypeModelElementTaggedValue_QNAME,
				ModelElementTaggedValue.class, CollaborationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ClassifierFeatureType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ClassifierFeatureType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Classifier.feature", scope = CollaborationType.class)
	public JAXBElement<ClassifierFeatureType> createCollaborationTypeClassifierFeature(ClassifierFeatureType value) {
		return new JAXBElement<ClassifierFeatureType>(_GeneralizationTypeClassifierFeature_QNAME,
				ClassifierFeatureType.class, CollaborationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link AssociationConnectionType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link AssociationConnectionType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Association.connection", scope = CollaborationType.class)
	public JAXBElement<AssociationConnectionType> createCollaborationTypeAssociationConnection(
			AssociationConnectionType value) {
		return new JAXBElement<AssociationConnectionType>(_GeneralizationTypeAssociationConnection_QNAME,
				AssociationConnectionType.class, CollaborationType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link InteractionType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link InteractionType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Interaction", scope = CollaborationType.CollaborationInteraction.class)
	public JAXBElement<InteractionType> createCollaborationTypeCollaborationInteractionInteraction(
			InteractionType value) {
		return new JAXBElement<InteractionType>(_CollaborationTypeCollaborationInteractionInteraction_QNAME,
				InteractionType.class, CollaborationType.CollaborationInteraction.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementStereotypeType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementStereotypeType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.stereotype", scope = ClassType.class)
	public JAXBElement<ModelElementStereotypeType> createClassTypeModelElementStereotype(
			ModelElementStereotypeType value) {
		return new JAXBElement<ModelElementStereotypeType>(_GeneralizationTypeModelElementStereotype_QNAME,
				ModelElementStereotypeType.class, ClassType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ModelElementTaggedValue }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ModelElementTaggedValue }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ModelElement.taggedValue", scope = ClassType.class)
	public JAXBElement<ModelElementTaggedValue> createClassTypeModelElementTaggedValue(ModelElementTaggedValue value) {
		return new JAXBElement<ModelElementTaggedValue>(_GeneralizationTypeModelElementTaggedValue_QNAME,
				ModelElementTaggedValue.class, ClassType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link ClassifierFeatureType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ClassifierFeatureType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Classifier.feature", scope = ClassType.class)
	public JAXBElement<ClassifierFeatureType> createClassTypeClassifierFeature(ClassifierFeatureType value) {
		return new JAXBElement<ClassifierFeatureType>(_GeneralizationTypeClassifierFeature_QNAME,
				ClassifierFeatureType.class, ClassType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link AssociationConnectionType }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link AssociationConnectionType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Association.connection", scope = ClassType.class)
	public JAXBElement<AssociationConnectionType> createClassTypeAssociationConnection(
			AssociationConnectionType value) {
		return new JAXBElement<AssociationConnectionType>(_GeneralizationTypeAssociationConnection_QNAME,
				AssociationConnectionType.class, ClassType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ClassifierRoleType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link ClassifierRoleType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "ClassifierRole", scope = NamespaceOwnedElementType.class)
	public JAXBElement<ClassifierRoleType> createNamespaceOwnedElementTypeClassifierRole(ClassifierRoleType value) {
		return new JAXBElement<ClassifierRoleType>(_NamespaceOwnedElementTypeClassifierRole_QNAME,
				ClassifierRoleType.class, NamespaceOwnedElementType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ClassType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link ClassType
	 *         }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Class", scope = NamespaceOwnedElementType.class)
	public JAXBElement<ClassType> createNamespaceOwnedElementTypeClass(ClassType value) {
		return new JAXBElement<ClassType>(_NamespaceOwnedElementTypeClass_QNAME, ClassType.class,
				NamespaceOwnedElementType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AssociationType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link AssociationType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Association", scope = NamespaceOwnedElementType.class)
	public JAXBElement<AssociationType> createNamespaceOwnedElementTypeAssociation(AssociationType value) {
		return new JAXBElement<AssociationType>(_NamespaceOwnedElementTypeAssociation_QNAME, AssociationType.class,
				NamespaceOwnedElementType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link GeneralizationType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link GeneralizationType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Generalization", scope = NamespaceOwnedElementType.class)
	public JAXBElement<GeneralizationType> createNamespaceOwnedElementTypeGeneralization(GeneralizationType value) {
		return new JAXBElement<GeneralizationType>(_NamespaceOwnedElementTypeGeneralization_QNAME,
				GeneralizationType.class, NamespaceOwnedElementType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CommentType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link CommentType
	 *         }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Comment", scope = NamespaceOwnedElementType.class)
	public JAXBElement<CommentType> createNamespaceOwnedElementTypeComment(CommentType value) {
		return new JAXBElement<CommentType>(_NamespaceOwnedElementTypeComment_QNAME, CommentType.class,
				NamespaceOwnedElementType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CollaborationType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link CollaborationType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Collaboration", scope = NamespaceOwnedElementType.class)
	public JAXBElement<CollaborationType> createNamespaceOwnedElementTypeCollaboration(CollaborationType value) {
		return new JAXBElement<CollaborationType>(_NamespaceOwnedElementTypeCollaboration_QNAME,
				CollaborationType.class, NamespaceOwnedElementType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link PackageType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link PackageType
	 *         }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Package", scope = NamespaceOwnedElementType.class)
	public JAXBElement<PackageType> createNamespaceOwnedElementTypePackage(PackageType value) {
		return new JAXBElement<PackageType>(_NamespaceOwnedElementTypePackage_QNAME, PackageType.class,
				NamespaceOwnedElementType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AssociationRoleType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link AssociationRoleType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "AssociationRole", scope = NamespaceOwnedElementType.class)
	public JAXBElement<AssociationRoleType> createNamespaceOwnedElementTypeAssociationRole(AssociationRoleType value) {
		return new JAXBElement<AssociationRoleType>(_NamespaceOwnedElementTypeAssociationRole_QNAME,
				AssociationRoleType.class, NamespaceOwnedElementType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DependencyType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 *         }{@code <}{@link DependencyType }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "Dependency", scope = NamespaceOwnedElementType.class)
	public JAXBElement<DependencyType> createNamespaceOwnedElementTypeDependency(DependencyType value) {
		return new JAXBElement<DependencyType>(_NamespaceOwnedElementTypeDependency_QNAME, DependencyType.class,
				NamespaceOwnedElementType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DataTypeType
	 * }{@code >}
	 * 
	 * @param value
	 *            Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link DataTypeType
	 *         }{@code >}
	 */
	@XmlElementDecl(namespace = "omg.org/UML1.3", name = "DataType", scope = NamespaceOwnedElementType.class)
	public JAXBElement<DataTypeType> createNamespaceOwnedElementTypeDataType(DataTypeType value) {
		return new JAXBElement<DataTypeType>(_NamespaceOwnedElementTypeDataType_QNAME, DataTypeType.class,
				NamespaceOwnedElementType.class, value);
	}

}
