//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 06:13:11 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "omg.org/UML1.3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cimug.compare.uml1_3;
